### ISSUE TITLE
AttributeError: module 'cache' has no attribute 'cache'

### ISSUE THREAD

**Issue by Asilvorcarp** [SubConv/SubConv-4-ZJU#1]
I followed the instructions at https://docs-sub-conv.geniucker.top/guide/deploy/vps.html,
and got error:
```
[2023-09-05 17:56:40,380] ERROR in app: Exception on /sub [GET]
Traceback (most recent call last):
  File "/Users/asc/mambaforge/envs/subconv/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/asc/mambaforge/envs/subconv/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/asc/mambaforge/envs/subconv/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/asc/mambaforge/envs/subconv/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/asc/repo/_cloned_/SubConv-4-ZJU/./api.py", line 79, in sub
    result = pack.pack(url=url, urlstandby=urlstandby, content=content, interval=interval, domain=domain, zju=zju, short=short)
  File "/Users/asc/repo/_cloned_/SubConv-4-ZJU/modules/pack.py", line 116, in pack
    result += ("rules:\n  - DOMAIN,{},DIRECT\n".format(domain) + cache.cache)
AttributeError: module 'cache' has no attribute 'cache'
```
And it seems not to be a public module called cache, because `pip3 install cache` did not solve the problem.

**Comment by Asilvorcarp** [comment]
run `python mkcache.py` first
